apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: langfuse-secrets
  namespace: langfuse
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: langfuse-secrets
    creationPolicy: Owner
  data:
    - secretKey: rds!db-b12f5d09-c246-4138-9aa9-56854cd154e3
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: password
    - secretKey: NEXTAUTH_SECRET
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: NEXTAUTH_SECRET
    - secretKey: SALT
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: SALT
    - secretKey: LANGFUSE_PUBLIC_KEY
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: LANGFUSE_PUBLIC_KEY
    - secretKey: LANGFUSE_SECRET_KEY
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: LANGFUSE_SECRET_KEY
    - secretKey: CLICKHOUSE_PASSWORD
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: CLICKHOUSE_PASSWORD
    - secretKey: REDIS_PASSWORD
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: REDIS_PASSWORD
    - secretKey: INIT_USER_EMAIL
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: INIT_USER_EMAIL
    - secretKey: INIT_USER_PASSWORD
      remoteRef:
        key: litellm-eks/langfuse-secrets
        property: INIT_USER_PASSWORD
